import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LayoutAdmin from "src/components/layout/admin/LayoutAdmin";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cinema",
  description: "Generated by Duy Nguyen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LayoutAdmin>
      {children}
    </LayoutAdmin>
  );
}
