import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Cinema",
    description: "Generated by Duy Nguyen",
};
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>
    )
}