import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppHeader from "src/components/header/app.header";

import AppFooter from "src/components/footer/app.footer";
import StoreProvider from "../StoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cinema",
  description: "Generated by Duy Nguyen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <StoreProvider>
        <AppHeader />
        {children}
        <AppFooter />
      </StoreProvider>
    </>
  );
}
